### Project specific config ###
language: ruby
dist: trusty
env: ATOM_CHANNEL=stable
os: linux
rvm: 2.4
script: skip

jobs:
  include:
    - stage: test
      env: ATOM_CHANNEL=stable

    - stage: test
      env: ATOM_CHANNEL=beta

    - stage: test
      language: node_js
      node_js: lts/*
      install:
        - npm install
      script:
        - commitlint-travis

    - stage: release
      before_deploy:
        - export PATH=${PATH}:${HOME}/atom/usr/bin/
        - nvm install lts/*
        - node --version
        - npm --version
        - npx --version
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

before_script:
  - ruby --version
  - erb --version

### Generic setup follows ###
install:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^greenkeeper/.*$/

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

stages:
  - test
  - name: release
    if: (NOT type = pull_request) AND branch = master
