version: 2

defaults: &defaults
  working_directory: /tmp/linter-erb
  parallelism: 1
  shell: /bin/bash --login
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
  docker:
    - image: arcanemagus/atom-docker-ci:stable
  steps:
    # Restore project state
    - attach_workspace:
        at: /tmp
    - run:
        name: Create VFB for Atom to run in
        command: /usr/local/bin/xvfb_start
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: sudo apt update
    - run: sudo apt install ruby-full -y --no-install-suggests --no-install-recommends
    - run:
        name: Atom version
        command: ${ATOM_SCRIPT_PATH} --version
    - run:
        name: APM version
        command: ${APM_SCRIPT_PATH} --version
    - run:
        name: Cleaning package
        command: ${APM_SCRIPT_PATH} clean
    - run:
        name: Package dependencies
        command: ${APM_SCRIPT_PATH} install
    - run:
        name: Package specs
        command: ${ATOM_SCRIPT_PATH} --test spec
    # Cache node_modules
    - save_cache:
        key: v3-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules

jobs:
  checkout_code:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # Restore node_modules from the last build
      - restore_cache:
          keys:
          # Get latest cache for this package.json
          - v3-dependencies-{{ checksum "package.json" }}
          # Fallback to the last available cache
          - v3-dependencies
      # Save project state for next steps
      - persist_to_workspace:
          root: /tmp
          paths:
            - linter-erb
  lint:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      # Restore project state
      - attach_workspace:
          at: /tmp
      - run:
          name: Node.js Version
          command: node --version
      - run:
          name: NPM Version
          command: npm --version
      - run:
          name: Install any remaining dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run lint
  stable:
    <<: *defaults
  beta:
    <<: *defaults
    docker:
      - image: arcanemagus/atom-docker-ci:beta

workflows:
  version: 2
  test_package:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - stable:
          requires:
            - lint
      - beta:
          requires:
            - lint
